"""'fix_User_column'

Revision ID: 04b795c9c4ca
Revises: 73d1fbf2075a
Create Date: 2024-03-26 23:14:20.522002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b795c9c4ca'
down_revision: Union[str, None] = '73d1fbf2075a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
