"""migration2

Revision ID: 1d1437f07573
Revises: b9df8c6be9eb
Create Date: 2024-02-08 22:30:52.620309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1437f07573'
down_revision: Union[str, None] = 'b9df8c6be9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'family_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'family_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
