"""'delete_members_from_family'

Revision ID: 73d1fbf2075a
Revises: f65933732993
Create Date: 2024-03-26 20:49:24.426223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d1fbf2075a'
down_revision: Union[str, None] = 'f65933732993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('members', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
