"""Full

Revision ID: f878c12b6943
Revises: 
Create Date: 2024-04-03 08:52:28.763717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f878c12b6943'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
                    sa.Column('family_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('family_name', sa.String(), nullable=False),
                    sa.Column('family_password', sa.String(), nullable=False),
                    sa.Column('expenses', sa.BigInteger(), nullable=False),
                    sa.Column('income', sa.BigInteger(), nullable=False),
                    sa.Column('balance', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('family_id')
                    )
    op.create_table('transaction_families',
                    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('type_transactions', sa.String(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('family_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('transaction_id')
                    )
    op.create_table('transaction_users',
                    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('type_transactions', sa.String(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('user_name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('transaction_id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('phone_number', sa.String(), nullable=False),
                    sa.Column('expenses', sa.BigInteger(), nullable=False),
                    sa.Column('income', sa.BigInteger(), nullable=False),
                    sa.Column('balance', sa.BigInteger(), nullable=False),
                    sa.Column('transactions', sa.Integer(), nullable=False),
                    sa.Column('family_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'telegram_id'),
                    sa.UniqueConstraint('phone_number'),
                    sa.UniqueConstraint('telegram_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('transaction_users')
    op.drop_table('transaction_families')
    op.drop_table('families')
    # ### end Alembic commands ###
